name: "Submit to Web Store"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Yarn packages
        uses: actions/cache@v3
        with:
          path: ~/.yarn-cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install Yarn
        run: npm install -g yarn
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build the extension
        run: yarn build
      - name: Package the extension into a zip artifact
        run: yarn package
      - name: Change directory and create zip artifact
        run: |
          cd build/firefox-mv2-prod
          zip -r ../firefox-mv2-prod.zip .
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
